export type HealthBand = 'excellent' | 'good' | 'fair' | 'poor';
export type OnboardingStage =
  | 'Contract Signed' |'Kickoff Meeting' |'Account Setup' |'Configuration' |'Training' |'First Login' |'First Value' |'Go Live' |'Success Handoff';

export type CustomerTier = 'SMB' | 'Mid-Market' | 'Enterprise';
export type Region = 'North America' | 'Europe' | 'Asia Pacific';
export type RiskLevel = 'Low' | 'Medium' | 'High' | 'Critical';

export interface Customer {
  id: string;
  company: string;
  industry: string;
  tier: CustomerTier;
  region: Region;
  healthScore: number;
  healthBand: HealthBand;
  stage: OnboardingStage;
  progress: number;
  manager: string;
  managerInitials: string;
  daysInStage: number;
  riskLevel: RiskLevel;
  riskScore: number;
  contractValue: number;
  employees: string;
  lastActivity: string;
  accountOwner: string;
  startDate: string;
  expectedGoLive: string;
}

export interface Task {
  id: string;
  title: string;
  customerId: string;
  customerName: string;
  owner: string;
  ownerInitials: string;
  priority: 'Critical' | 'High' | 'Medium' | 'Low';
  dueDate: string;
  status: 'Backlog' | 'In Progress' | 'Blocked' | 'In Review' | 'Completed';
  progress: number;
  milestone: string;
  hasBlocker: boolean;
  isEscalated: boolean;
  dependsOn: string | null;
  description: string;
  createdAt: string;
}

export interface RiskAlert {
  id: string;
  customerId: string;
  company: string;
  tier: CustomerTier;
  issue: string;
  severity: 'Critical' | 'High' | 'Medium';
  daysSinceLastActivity: number;
  manager: string;
  revenueAtRisk: number;
}

export interface AIInsight {
  id: string;
  type: 'risk' | 'opportunity' | 'action';
  title: string;
  description: string;
  affectedCustomers: number;
  impact: 'High' | 'Medium' | 'Low';
}

export interface ActivityItem {
  id: string;
  actor: string;
  actorInitials: string;
  action: string;
  target: string;
  timestamp: string;
  type: 'milestone' | 'task' | 'risk' | 'note' | 'escalation';
}

export const managers = [
  { name: 'Sarah Chen', initials: 'SC' },
  { name: 'Marcus Webb', initials: 'MW' },
  { name: 'Priya Nair', initials: 'PN' },
  { name: 'Jordan Ellis', initials: 'JE' },
  { name: 'Aiko Tanaka', initials: 'AT' },
  { name: 'Daniel Osei', initials: 'DO' },
  { name: 'Lena Müller', initials: 'LM' },
  { name: 'Ryan Castillo', initials: 'RC' },
  { name: 'Fatima Al-Rashid', initials: 'FA' },
  { name: 'Chris Nakamura', initials: 'CN' },
];

export const customers: Customer[] = [
  {
    id: 'cust-001',
    company: 'Meridian Financial Group',
    industry: 'Financial Services',
    tier: 'Enterprise',
    region: 'North America',
    healthScore: 82,
    healthBand: 'good',
    stage: 'Configuration',
    progress: 45,
    manager: 'Sarah Chen',
    managerInitials: 'SC',
    daysInStage: 4,
    riskLevel: 'Low',
    riskScore: 18,
    contractValue: 240000,
    employees: '1,200–2,500',
    lastActivity: '2026-07-23',
    accountOwner: 'Sarah Chen',
    startDate: '2026-06-10',
    expectedGoLive: '2026-08-15',
  },
  {
    id: 'cust-002',
    company: 'Apex Retail Solutions',
    industry: 'Retail & E-Commerce',
    tier: 'Mid-Market',
    region: 'North America',
    healthScore: 54,
    healthBand: 'fair',
    stage: 'Training',
    progress: 62,
    manager: 'Marcus Webb',
    managerInitials: 'MW',
    daysInStage: 14,
    riskLevel: 'High',
    riskScore: 72,
    contractValue: 96000,
    employees: '200–500',
    lastActivity: '2026-07-18',
    accountOwner: 'Marcus Webb',
    startDate: '2026-05-20',
    expectedGoLive: '2026-07-30',
  },
  {
    id: 'cust-003',
    company: 'Solaris Health Systems',
    industry: 'Healthcare',
    tier: 'Enterprise',
    region: 'North America',
    healthScore: 91,
    healthBand: 'excellent',
    stage: 'First Value',
    progress: 78,
    manager: 'Priya Nair',
    managerInitials: 'PN',
    daysInStage: 2,
    riskLevel: 'Low',
    riskScore: 12,
    contractValue: 360000,
    employees: '5,000+',
    lastActivity: '2026-07-24',
    accountOwner: 'Priya Nair',
    startDate: '2026-05-01',
    expectedGoLive: '2026-08-01',
  },
  {
    id: 'cust-004',
    company: 'NorthBridge Logistics',
    industry: 'Logistics & Supply Chain',
    tier: 'Mid-Market',
    region: 'Europe',
    healthScore: 38,
    healthBand: 'poor',
    stage: 'Account Setup',
    progress: 28,
    manager: 'Lena Müller',
    managerInitials: 'LM',
    daysInStage: 21,
    riskLevel: 'Critical',
    riskScore: 91,
    contractValue: 84000,
    employees: '300–800',
    lastActivity: '2026-07-10',
    accountOwner: 'Lena Müller',
    startDate: '2026-06-01',
    expectedGoLive: '2026-08-20',
  },
  {
    id: 'cust-005',
    company: 'Quantum Dynamics Corp',
    industry: 'Manufacturing',
    tier: 'Enterprise',
    region: 'North America',
    healthScore: 76,
    healthBand: 'good',
    stage: 'Go Live',
    progress: 90,
    manager: 'Jordan Ellis',
    managerInitials: 'JE',
    daysInStage: 3,
    riskLevel: 'Low',
    riskScore: 22,
    contractValue: 480000,
    employees: '3,000–5,000',
    lastActivity: '2026-07-23',
    accountOwner: 'Jordan Ellis',
    startDate: '2026-04-15',
    expectedGoLive: '2026-07-28',
  },
  {
    id: 'cust-006',
    company: 'Sakura Digital Agency',
    industry: 'Marketing & Advertising',
    tier: 'SMB',
    region: 'Asia Pacific',
    healthScore: 68,
    healthBand: 'good',
    stage: 'First Login',
    progress: 70,
    manager: 'Aiko Tanaka',
    managerInitials: 'AT',
    daysInStage: 6,
    riskLevel: 'Medium',
    riskScore: 41,
    contractValue: 28800,
    employees: '50–150',
    lastActivity: '2026-07-22',
    accountOwner: 'Aiko Tanaka',
    startDate: '2026-06-15',
    expectedGoLive: '2026-08-05',
  },
  {
    id: 'cust-007',
    company: 'Vantage Capital Partners',
    industry: 'Financial Services',
    tier: 'Enterprise',
    region: 'Europe',
    healthScore: 44,
    healthBand: 'poor',
    stage: 'Configuration',
    progress: 38,
    manager: 'Daniel Osei',
    managerInitials: 'DO',
    daysInStage: 18,
    riskLevel: 'Critical',
    riskScore: 88,
    contractValue: 320000,
    employees: '800–1,500',
    lastActivity: '2026-07-12',
    accountOwner: 'Daniel Osei',
    startDate: '2026-05-28',
    expectedGoLive: '2026-08-10',
  },
  {
    id: 'cust-008',
    company: 'BlueSky Pharmaceuticals',
    industry: 'Pharmaceuticals',
    tier: 'Enterprise',
    region: 'North America',
    healthScore: 85,
    healthBand: 'excellent',
    stage: 'Training',
    progress: 58,
    manager: 'Ryan Castillo',
    managerInitials: 'RC',
    daysInStage: 5,
    riskLevel: 'Low',
    riskScore: 16,
    contractValue: 288000,
    employees: '2,000–4,000',
    lastActivity: '2026-07-24',
    accountOwner: 'Ryan Castillo',
    startDate: '2026-06-20',
    expectedGoLive: '2026-08-25',
  },
  {
    id: 'cust-009',
    company: 'Clearwater Energy',
    industry: 'Energy & Utilities',
    tier: 'Mid-Market',
    region: 'North America',
    healthScore: 61,
    healthBand: 'fair',
    stage: 'Kickoff Meeting',
    progress: 12,
    manager: 'Fatima Al-Rashid',
    managerInitials: 'FA',
    daysInStage: 8,
    riskLevel: 'Medium',
    riskScore: 48,
    contractValue: 72000,
    employees: '400–900',
    lastActivity: '2026-07-20',
    accountOwner: 'Fatima Al-Rashid',
    startDate: '2026-07-10',
    expectedGoLive: '2026-09-15',
  },
  {
    id: 'cust-010',
    company: 'Titan Aerospace',
    industry: 'Aerospace & Defense',
    tier: 'Enterprise',
    region: 'North America',
    healthScore: 79,
    healthBand: 'good',
    stage: 'Account Setup',
    progress: 22,
    manager: 'Chris Nakamura',
    managerInitials: 'CN',
    daysInStage: 7,
    riskLevel: 'Low',
    riskScore: 28,
    contractValue: 520000,
    employees: '10,000+',
    lastActivity: '2026-07-22',
    accountOwner: 'Chris Nakamura',
    startDate: '2026-07-01',
    expectedGoLive: '2026-09-30',
  },
  {
    id: 'cust-011',
    company: 'GreenLeaf Foods',
    industry: 'Food & Beverage',
    tier: 'SMB',
    region: 'Europe',
    healthScore: 72,
    healthBand: 'good',
    stage: 'Configuration',
    progress: 50,
    manager: 'Lena Müller',
    managerInitials: 'LM',
    daysInStage: 9,
    riskLevel: 'Medium',
    riskScore: 35,
    contractValue: 36000,
    employees: '100–250',
    lastActivity: '2026-07-21',
    accountOwner: 'Lena Müller',
    startDate: '2026-06-08',
    expectedGoLive: '2026-08-10',
  },
  {
    id: 'cust-012',
    company: 'Ironclad Cybersecurity',
    industry: 'Technology',
    tier: 'Mid-Market',
    region: 'North America',
    healthScore: 88,
    healthBand: 'excellent',
    stage: 'First Value',
    progress: 82,
    manager: 'Sarah Chen',
    managerInitials: 'SC',
    daysInStage: 3,
    riskLevel: 'Low',
    riskScore: 10,
    contractValue: 144000,
    employees: '300–600',
    lastActivity: '2026-07-24',
    accountOwner: 'Sarah Chen',
    startDate: '2026-05-15',
    expectedGoLive: '2026-07-31',
  },
  {
    id: 'cust-013',
    company: 'Nexus Property Group',
    industry: 'Real Estate',
    tier: 'Mid-Market',
    region: 'Asia Pacific',
    healthScore: 57,
    healthBand: 'fair',
    stage: 'Training',
    progress: 60,
    manager: 'Aiko Tanaka',
    managerInitials: 'AT',
    daysInStage: 11,
    riskLevel: 'High',
    riskScore: 65,
    contractValue: 108000,
    employees: '200–400',
    lastActivity: '2026-07-17',
    accountOwner: 'Aiko Tanaka',
    startDate: '2026-05-25',
    expectedGoLive: '2026-08-12',
  },
  {
    id: 'cust-014',
    company: 'Cascade Insurance Group',
    industry: 'Insurance',
    tier: 'Enterprise',
    region: 'North America',
    healthScore: 93,
    healthBand: 'excellent',
    stage: 'Go Live',
    progress: 92,
    manager: 'Marcus Webb',
    managerInitials: 'MW',
    daysInStage: 2,
    riskLevel: 'Low',
    riskScore: 8,
    contractValue: 396000,
    employees: '2,500–5,000',
    lastActivity: '2026-07-24',
    accountOwner: 'Marcus Webb',
    startDate: '2026-04-01',
    expectedGoLive: '2026-07-26',
  },
  {
    id: 'cust-015',
    company: 'Starfield Media',
    industry: 'Media & Entertainment',
    tier: 'SMB',
    region: 'Europe',
    healthScore: 47,
    healthBand: 'poor',
    stage: 'Account Setup',
    progress: 18,
    manager: 'Daniel Osei',
    managerInitials: 'DO',
    daysInStage: 16,
    riskLevel: 'High',
    riskScore: 78,
    contractValue: 24000,
    employees: '30–100',
    lastActivity: '2026-07-14',
    accountOwner: 'Daniel Osei',
    startDate: '2026-06-25',
    expectedGoLive: '2026-08-30',
  },
];

export const tasks: Task[] = [
  {
    id: 'task-001',
    title: 'Complete SSO configuration for Meridian',
    customerId: 'cust-001',
    customerName: 'Meridian Financial Group',
    owner: 'Sarah Chen',
    ownerInitials: 'SC',
    priority: 'High',
    dueDate: '2026-07-26',
    status: 'In Progress',
    progress: 65,
    milestone: 'Configuration',
    hasBlocker: false,
    isEscalated: false,
    dependsOn: null,
    description: 'Configure SSO with Okta integration per security requirements.',
    createdAt: '2026-07-20',
  },
  {
    id: 'task-002',
    title: 'Schedule training sessions — Apex Retail',
    customerId: 'cust-002',
    customerName: 'Apex Retail Solutions',
    owner: 'Marcus Webb',
    ownerInitials: 'MW',
    priority: 'Critical',
    dueDate: '2026-07-25',
    status: 'Blocked',
    progress: 10,
    milestone: 'Training',
    hasBlocker: true,
    isEscalated: true,
    dependsOn: 'task-008',
    description: 'Blocked pending customer availability confirmation.',
    createdAt: '2026-07-15',
  },
  {
    id: 'task-003',
    title: 'API integration review — Solaris Health',
    customerId: 'cust-003',
    customerName: 'Solaris Health Systems',
    owner: 'Priya Nair',
    ownerInitials: 'PN',
    priority: 'Medium',
    dueDate: '2026-07-28',
    status: 'In Review',
    progress: 90,
    milestone: 'First Value',
    hasBlocker: false,
    isEscalated: false,
    dependsOn: null,
    description: 'Final review of HL7 FHIR API integration before sign-off.',
    createdAt: '2026-07-18',
  },
  {
    id: 'task-004',
    title: 'NorthBridge — escalate setup delay',
    customerId: 'cust-004',
    customerName: 'NorthBridge Logistics',
    owner: 'Lena Müller',
    ownerInitials: 'LM',
    priority: 'Critical',
    dueDate: '2026-07-24',
    status: 'Blocked',
    progress: 5,
    milestone: 'Account Setup',
    hasBlocker: true,
    isEscalated: true,
    dependsOn: null,
    description: 'Customer IT team unresponsive for 21 days. Executive escalation required.',
    createdAt: '2026-07-03',
  },
  {
    id: 'task-005',
    title: 'Quantum Dynamics — Go Live checklist',
    customerId: 'cust-005',
    customerName: 'Quantum Dynamics Corp',
    owner: 'Jordan Ellis',
    ownerInitials: 'JE',
    priority: 'High',
    dueDate: '2026-07-27',
    status: 'In Progress',
    progress: 80,
    milestone: 'Go Live',
    hasBlocker: false,
    isEscalated: false,
    dependsOn: null,
    description: 'Complete final pre-launch checklist items.',
    createdAt: '2026-07-21',
  },
  {
    id: 'task-006',
    title: 'Sakura Digital — admin user setup',
    customerId: 'cust-006',
    customerName: 'Sakura Digital Agency',
    owner: 'Aiko Tanaka',
    ownerInitials: 'AT',
    priority: 'Medium',
    dueDate: '2026-07-29',
    status: 'In Progress',
    progress: 45,
    milestone: 'First Login',
    hasBlocker: false,
    isEscalated: false,
    dependsOn: null,
    description: 'Set up admin accounts for 3 power users.',
    createdAt: '2026-07-22',
  },
  {
    id: 'task-007',
    title: 'Vantage Capital — security review',
    customerId: 'cust-007',
    customerName: 'Vantage Capital Partners',
    owner: 'Daniel Osei',
    ownerInitials: 'DO',
    priority: 'Critical',
    dueDate: '2026-07-25',
    status: 'Blocked',
    progress: 20,
    milestone: 'Configuration',
    hasBlocker: true,
    isEscalated: true,
    dependsOn: null,
    description: 'Pending compliance team approval for data residency requirements.',
    createdAt: '2026-07-08',
  },
  {
    id: 'task-008',
    title: 'Apex — send training schedule template',
    customerId: 'cust-002',
    customerName: 'Apex Retail Solutions',
    owner: 'Marcus Webb',
    ownerInitials: 'MW',
    priority: 'High',
    dueDate: '2026-07-24',
    status: 'Backlog',
    progress: 0,
    milestone: 'Training',
    hasBlocker: false,
    isEscalated: false,
    dependsOn: null,
    description: 'Draft and send training schedule template for customer review.',
    createdAt: '2026-07-20',
  },
  {
    id: 'task-009',
    title: 'BlueSky Pharma — compliance documentation',
    customerId: 'cust-008',
    customerName: 'BlueSky Pharmaceuticals',
    owner: 'Ryan Castillo',
    ownerInitials: 'RC',
    priority: 'High',
    dueDate: '2026-07-30',
    status: 'In Progress',
    progress: 55,
    milestone: 'Training',
    hasBlocker: false,
    isEscalated: false,
    dependsOn: null,
    description: 'Prepare FDA 21 CFR Part 11 compliance documentation.',
    createdAt: '2026-07-19',
  },
  {
    id: 'task-010',
    title: 'Clearwater — kickoff meeting preparation',
    customerId: 'cust-009',
    customerName: 'Clearwater Energy',
    owner: 'Fatima Al-Rashid',
    ownerInitials: 'FA',
    priority: 'Medium',
    dueDate: '2026-07-26',
    status: 'In Progress',
    progress: 70,
    milestone: 'Kickoff Meeting',
    hasBlocker: false,
    isEscalated: false,
    dependsOn: null,
    description: 'Prepare kickoff deck and stakeholder alignment materials.',
    createdAt: '2026-07-18',
  },
  {
    id: 'task-011',
    title: 'Titan Aerospace — NDA and DPA review',
    customerId: 'cust-010',
    customerName: 'Titan Aerospace',
    owner: 'Chris Nakamura',
    ownerInitials: 'CN',
    priority: 'High',
    dueDate: '2026-07-28',
    status: 'In Review',
    progress: 85,
    milestone: 'Account Setup',
    hasBlocker: false,
    isEscalated: false,
    dependsOn: null,
    description: 'Legal review of amended NDA and Data Processing Agreement.',
    createdAt: '2026-07-17',
  },
  {
    id: 'task-012',
    title: 'Ironclad — success metrics baseline',
    customerId: 'cust-012',
    customerName: 'Ironclad Cybersecurity',
    owner: 'Sarah Chen',
    ownerInitials: 'SC',
    priority: 'Medium',
    dueDate: '2026-07-31',
    status: 'In Progress',
    progress: 40,
    milestone: 'First Value',
    hasBlocker: false,
    isEscalated: false,
    dependsOn: null,
    description: 'Establish baseline threat detection metrics pre-launch.',
    createdAt: '2026-07-21',
  },
  {
    id: 'task-013',
    title: 'Nexus Property — retrain on data import',
    customerId: 'cust-013',
    customerName: 'Nexus Property Group',
    owner: 'Aiko Tanaka',
    ownerInitials: 'AT',
    priority: 'High',
    dueDate: '2026-07-27',
    status: 'Backlog',
    progress: 0,
    milestone: 'Training',
    hasBlocker: false,
    isEscalated: false,
    dependsOn: null,
    description: 'Customer requested additional session on bulk property data import.',
    createdAt: '2026-07-22',
  },
  {
    id: 'task-014',
    title: 'Cascade Insurance — success handoff prep',
    customerId: 'cust-014',
    customerName: 'Cascade Insurance Group',
    owner: 'Marcus Webb',
    ownerInitials: 'MW',
    priority: 'Medium',
    dueDate: '2026-07-28',
    status: 'In Progress',
    progress: 60,
    milestone: 'Go Live',
    hasBlocker: false,
    isEscalated: false,
    dependsOn: null,
    description: 'Prepare handoff documentation for long-term CS team.',
    createdAt: '2026-07-20',
  },
  {
    id: 'task-015',
    title: 'Starfield Media — IT contact escalation',
    customerId: 'cust-015',
    customerName: 'Starfield Media',
    owner: 'Daniel Osei',
    ownerInitials: 'DO',
    priority: 'Critical',
    dueDate: '2026-07-24',
    status: 'Blocked',
    progress: 0,
    milestone: 'Account Setup',
    hasBlocker: true,
    isEscalated: true,
    dependsOn: null,
    description: 'No IT contact provided. Cannot proceed with account provisioning.',
    createdAt: '2026-07-14',
  },
  {
    id: 'task-016',
    title: 'GreenLeaf — workflow automation config',
    customerId: 'cust-011',
    customerName: 'GreenLeaf Foods',
    owner: 'Lena Müller',
    ownerInitials: 'LM',
    priority: 'Low',
    dueDate: '2026-08-02',
    status: 'Backlog',
    progress: 0,
    milestone: 'Configuration',
    hasBlocker: false,
    isEscalated: false,
    dependsOn: 'task-017',
    description: 'Configure automated approval workflows for purchase orders.',
    createdAt: '2026-07-22',
  },
  {
    id: 'task-017',
    title: 'GreenLeaf — data migration validation',
    customerId: 'cust-011',
    customerName: 'GreenLeaf Foods',
    owner: 'Lena Müller',
    ownerInitials: 'LM',
    priority: 'Medium',
    dueDate: '2026-07-30',
    status: 'In Progress',
    progress: 35,
    milestone: 'Configuration',
    hasBlocker: false,
    isEscalated: false,
    dependsOn: null,
    description: 'Validate migrated ERP data integrity before workflow config.',
    createdAt: '2026-07-18',
  },
  {
    id: 'task-018',
    title: 'Quantum Dynamics — user acceptance testing',
    customerId: 'cust-005',
    customerName: 'Quantum Dynamics Corp',
    owner: 'Jordan Ellis',
    ownerInitials: 'JE',
    priority: 'High',
    dueDate: '2026-07-26',
    status: 'Completed',
    progress: 100,
    milestone: 'Go Live',
    hasBlocker: false,
    isEscalated: false,
    dependsOn: null,
    description: 'UAT sign-off from 6 department heads.',
    createdAt: '2026-07-10',
  },
  {
    id: 'task-019',
    title: 'Cascade Insurance — final data validation',
    customerId: 'cust-014',
    customerName: 'Cascade Insurance Group',
    owner: 'Marcus Webb',
    ownerInitials: 'MW',
    priority: 'High',
    dueDate: '2026-07-25',
    status: 'Completed',
    progress: 100,
    milestone: 'Go Live',
    hasBlocker: false,
    isEscalated: false,
    dependsOn: null,
    description: 'Final validation of policy data migration.',
    createdAt: '2026-07-15',
  },
  {
    id: 'task-020',
    title: 'Ironclad — threat model documentation',
    customerId: 'cust-012',
    customerName: 'Ironclad Cybersecurity',
    owner: 'Sarah Chen',
    ownerInitials: 'SC',
    priority: 'Low',
    dueDate: '2026-08-05',
    status: 'Backlog',
    progress: 0,
    milestone: 'First Value',
    hasBlocker: false,
    isEscalated: false,
    dependsOn: 'task-012',
    description: 'Document threat model based on baseline metrics.',
    createdAt: '2026-07-23',
  },
];

export const riskAlerts: RiskAlert[] = [
  {
    id: 'alert-001',
    customerId: 'cust-004',
    company: 'NorthBridge Logistics',
    tier: 'Mid-Market',
    issue: 'IT team unresponsive for 21 days — Account Setup stalled',
    severity: 'Critical',
    daysSinceLastActivity: 14,
    manager: 'Lena Müller',
    revenueAtRisk: 84000,
  },
  {
    id: 'alert-002',
    customerId: 'cust-007',
    company: 'Vantage Capital Partners',
    tier: 'Enterprise',
    issue: 'Compliance approval pending 18 days — Go Live at risk',
    severity: 'Critical',
    daysSinceLastActivity: 12,
    manager: 'Daniel Osei',
    revenueAtRisk: 320000,
  },
  {
    id: 'alert-003',
    customerId: 'cust-002',
    company: 'Apex Retail Solutions',
    tier: 'Mid-Market',
    issue: 'Training blocked — customer availability not confirmed',
    severity: 'High',
    daysSinceLastActivity: 6,
    manager: 'Marcus Webb',
    revenueAtRisk: 96000,
  },
  {
    id: 'alert-004',
    customerId: 'cust-015',
    company: 'Starfield Media',
    tier: 'SMB',
    issue: 'No IT contact provided — account provisioning blocked',
    severity: 'High',
    daysSinceLastActivity: 10,
    manager: 'Daniel Osei',
    revenueAtRisk: 24000,
  },
  {
    id: 'alert-005',
    customerId: 'cust-013',
    company: 'Nexus Property Group',
    tier: 'Mid-Market',
    issue: 'Training stalled — 11 days in stage, no progress update',
    severity: 'Medium',
    daysSinceLastActivity: 7,
    manager: 'Aiko Tanaka',
    revenueAtRisk: 108000,
  },
];

export const aiInsights: AIInsight[] = [
  {
    id: 'insight-001',
    type: 'risk',
    title: '3 Enterprise customers likely to miss Go Live targets',
    description:
      'NorthBridge Logistics, Vantage Capital, and Starfield Media show configuration delays exceeding 14 days with no recent stakeholder engagement. Historical patterns indicate 78% probability of 3–4 week Go Live slippage without immediate executive intervention.',
    affectedCustomers: 3,
    impact: 'High',
  },
  {
    id: 'insight-002',
    type: 'opportunity',
    title: 'Cascade Insurance approaching handoff — expansion signal',
    description:
      'Cascade Insurance Group reaches Go Live this week with 93 health score. Their usage patterns mirror 4 previous customers who expanded ARR by 40% within 90 days. Recommend scheduling expansion discovery call during handoff.',
    affectedCustomers: 1,
    impact: 'High',
  },
  {
    id: 'insight-003',
    type: 'action',
    title: 'Standardize training delivery to reduce stage duration by 34%',
    description:
      'Analysis of 28 completed onboardings shows customers receiving structured training modules complete in avg 8.2 days vs 12.4 days for ad-hoc sessions. Recommend deploying the Solaris training template across all active Mid-Market onboardings.',
    affectedCustomers: 8,
    impact: 'Medium',
  },
];

export const activityFeed: ActivityItem[] = [
  {
    id: 'act-001',
    actor: 'Priya Nair',
    actorInitials: 'PN',
    action: 'completed milestone',
    target: 'First Login — Solaris Health Systems',
    timestamp: '2026-07-24T09:14:00',
    type: 'milestone',
  },
  {
    id: 'act-002',
    actor: 'Jordan Ellis',
    actorInitials: 'JE',
    action: 'marked UAT complete',
    target: 'Quantum Dynamics Corp',
    timestamp: '2026-07-24T08:52:00',
    type: 'task',
  },
  {
    id: 'act-003',
    actor: 'Daniel Osei',
    actorInitials: 'DO',
    action: 'escalated task',
    target: 'Vantage Capital — security review',
    timestamp: '2026-07-23T17:30:00',
    type: 'escalation',
  },
  {
    id: 'act-004',
    actor: 'Marcus Webb',
    actorInitials: 'MW',
    action: 'added note',
    target: 'Apex Retail Solutions — training delay',
    timestamp: '2026-07-23T15:20:00',
    type: 'note',
  },
  {
    id: 'act-005',
    actor: 'Lena Müller',
    actorInitials: 'LM',
    action: 'raised risk flag',
    target: 'NorthBridge Logistics — IT unresponsive',
    timestamp: '2026-07-23T14:05:00',
    type: 'risk',
  },
  {
    id: 'act-006',
    actor: 'Sarah Chen',
    actorInitials: 'SC',
    action: 'completed milestone',
    target: 'Configuration — Meridian Financial Group',
    timestamp: '2026-07-23T11:40:00',
    type: 'milestone',
  },
  {
    id: 'act-007',
    actor: 'Ryan Castillo',
    actorInitials: 'RC',
    action: 'updated task progress',
    target: 'BlueSky Pharma — compliance docs (55%)',
    timestamp: '2026-07-23T10:15:00',
    type: 'task',
  },
];

export const ttvTrendData = [
  { week: 'W14', avgTTV: 58, target: 52, completions: 2 },
  { week: 'W15', avgTTV: 54, target: 52, completions: 3 },
  { week: 'W16', avgTTV: 61, target: 52, completions: 1 },
  { week: 'W17', avgTTV: 56, target: 52, completions: 4 },
  { week: 'W18', avgTTV: 49, target: 52, completions: 3 },
  { week: 'W19', avgTTV: 52, target: 52, completions: 2 },
  { week: 'W20', avgTTV: 47, target: 52, completions: 5 },
  { week: 'W21', avgTTV: 44, target: 52, completions: 4 },
  { week: 'W22', avgTTV: 50, target: 52, completions: 3 },
  { week: 'W23', avgTTV: 46, target: 52, completions: 6 },
  { week: 'W24', avgTTV: 43, target: 52, completions: 4 },
  { week: 'W25', avgTTV: 41, target: 52, completions: 5 },
];

export const stageDistributionData = [
  { stage: 'Contract Signed', count: 3 },
  { stage: 'Kickoff', count: 4 },
  { stage: 'Account Setup', count: 6 },
  { stage: 'Configuration', count: 9 },
  { stage: 'Training', count: 11 },
  { stage: 'First Login', count: 7 },
  { stage: 'First Value', count: 5 },
  { stage: 'Go Live', count: 3 },
  { stage: 'Handoff', count: 2 },
];

export const healthDistributionData = [
  { band: 'Excellent (80–100)', count: 12, fill: '#16A34A' },
  { band: 'Good (60–79)', count: 18, fill: '#65A30D' },
  { band: 'Fair (40–59)', count: 11, fill: '#D97706' },
  { band: 'Poor (0–39)', count: 9, fill: '#DC2626' },
];